"use client";

import { useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { BookOpen, Zap, Code2, Globe, Download, Key, ChevronRight, Search, Terminal, FileText, Settings, ArrowRight, Check, Copy, ExternalLink, Sparkles, Layout, GitBranch } from 'lucide-react';
import { useTranslations } from "next-intl";
import { Reveal } from "@/components/Reveal";
import { fadeInUp, staggerContainer } from "@/lib/motion";

const DOC_SECTIONS = [
  {
    key: "getting-started",
    label: "Getting Started",
    icon: Zap,
    color: "text-violet-600",
    bg: "bg-violet-100",
    items: ["Introduction", "Quick Start", "Your First Site", "Credits & Billing"],
  },
  {
    key: "generating",
    label: "Generating Sites",
    icon: Sparkles,
    color: "text-emerald-600",
    bg: "bg-emerald-100",
    items: ["Writing Prompts", "Design Dials", "Aesthetic Presets", "Multi-page Sites"],
  },
  {
    key: "code-export",
    label: "Code & Export",
    icon: Code2,
    color: "text-blue-600",
    bg: "bg-blue-100",
    items: ["Downloading Code", "GitHub Push", "Project Structure", "TypeScript Setup"],
  },
  {
    key: "deployment",
    label: "Deployment",
    icon: Globe,
    color: "text-orange-600",
    bg: "bg-orange-100",
    items: ["Vercel Deploy", "Netlify Deploy", "Custom Domains", "Environment Variables"],
  },
  {
    key: "api",
    label: "API Reference",
    icon: Terminal,
    color: "text-pink-600",
    bg: "bg-pink-100",
    items: ["Authentication", "Generate Endpoint", "Projects API", "Webhooks"],
  },
  {
    key: "settings",
    label: "Account & Settings",
    icon: Settings,
    color: "text-gray-600",
    bg: "bg-gray-100",
    items: ["Profile", "Credit History", "Notifications", "Team Access"],
  },
];

const QUICK_START_STEPS = [
  {
    step: "01",
    title: "Create an account",
    description: "Sign up for free and get 50 generation credits instantly. No credit card required.",
    color: "bg-violet-600",
  },
  {
    step: "02",
    title: "Describe your site",
    description: "Type what you want in plain English. Include brand, style, content, and any specific pages.",
    color: "bg-blue-600",
  },
  {
    step: "03",
    title: "Preview and export",
    description: "Watch your site build in real time. Download the full Next.js source code when ready.",
    color: "bg-emerald-600",
  },
];

const CODE_SAMPLES = [
  {
    key: "prompt",
    label: "Example Prompt",
    language: "text",
    code: `Create a SaaS landing page for "Flowly" — a project management tool.
Use a dark theme with purple accents. Include:
- Hero with animated headline
- 3-column features section
- Pricing table (Free / Pro / Enterprise)
- FAQ accordion
- CTA section with gradient background`,
  },
  {
    key: "api",
    label: "API Request",
    language: "bash",
    code: `curl -X POST https://builder.hotcode.ai/api/generate \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "prompt": "A portfolio site for a UX designer",
    "aesthetic": "minimal-editorial",
    "pages": ["home", "work", "about", "contact"]
  }'`,
  },
  {
    key: "response",
    label: "API Response",
    language: "json",
    code: `{
  "id": "proj_abc123",
  "status": "generating",
  "preview_url": "https://preview.hotcode.ai/proj_abc123",
  "credits_used": 1,
  "estimated_seconds": 45
}`,
  },
];

const FAQ_ITEMS = [
  {
    q: "What is a generation credit?",
    a: "One credit equals one complete website generation. Each time you submit a prompt and Builder produces a full site, one credit is consumed. Editing and re-generating the same project uses additional credits.",
  },
  {
    q: "Do credits expire?",
    a: "Paid credits never expire. Free tier credits reset monthly. You can top up at any time by purchasing a credit pack.",
  },
  {
    q: "Can I use the generated code commercially?",
    a: "Yes. All code generated by Builder is yours to use, modify, and deploy commercially without restriction.",
  },
  {
    q: "What tech stack does Builder output?",
    a: "Builder generates Next.js 14 App Router projects with TypeScript, Tailwind CSS, framer-motion, and lucide-react. The output is clean, production-ready code you can open in any editor.",
  },
  {
    q: "How do I push to GitHub?",
    a: "Connect your GitHub account in Settings, then click 'Push to GitHub' on any project. Builder creates a new repository and pushes the full source code automatically.",
  },
];

function CodeBlock({ code, language, label }: { code: string; language: string; label: string }) {
  const [copied, setCopied] = useState(false);

  function handleCopy() {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <div className="rounded-xl border border-black/8 overflow-hidden shadow-[0_1px_2px_rgba(0,0,0,0.04),0_4px_16px_-4px_rgba(0,0,0,0.08)]">
      <div className="flex items-center justify-between px-4 py-2.5 bg-gray-50 border-b border-black/8">
        <span className="text-xs font-medium text-gray-500">{label}</span>
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 text-xs text-gray-500 hover:text-gray-800 transition-colors duration-200"
          aria-label="Copy code"
        >
          {copied ? <Check className="h-3.5 w-3.5 text-emerald-600" /> : <Copy className="h-3.5 w-3.5" />}
          {copied ? "Copied" : "Copy"}
        </button>
      </div>
      <pre className="p-4 overflow-x-auto bg-gray-950 text-gray-100 text-sm leading-relaxed">
        <code>{code}</code>
      </pre>
    </div>
  );
}

function FaqItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border border-black/8 rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen((v) => !v)}
        className="w-full flex items-center justify-between px-5 py-4 text-left hover:bg-gray-50 transition-colors duration-200"
        aria-expanded={open}
      >
        <span className="font-medium text-gray-900 text-sm">{q}</span>
        <ChevronRight
          className={`h-4 w-4 text-gray-400 flex-shrink-0 transition-transform duration-200 ${open ? "rotate-90" : ""}`}
        />
      </button>
      {open && (
        <div className="px-5 pb-4 text-sm text-gray-600 leading-relaxed border-t border-black/5 pt-3">
          {a}
        </div>
      )}
    </div>
  );
}

export default function DocsPage() {
  const t = useTranslations();
  const [activeCode, setActiveCode] = useState("prompt");
  const [searchQuery, setSearchQuery] = useState("");

  const activeSample = CODE_SAMPLES.find((s) => s.key === activeCode) ?? CODE_SAMPLES[0];

  const filteredSections = DOC_SECTIONS.filter((section) => {
    if (!searchQuery.trim()) return true;
    const q = searchQuery.toLowerCase();
    return (
      section.label.toLowerCase().includes(q) ||
      section.items.some((item) => item.toLowerCase().includes(q))
    );
  });

  return (
    <main className="min-h-screen bg-[#f7f7fb]">
      {/* Hero */}
      <Reveal>
        <section className="relative overflow-hidden bg-gradient-to-b from-violet-50 via-white to-[#f7f7fb] border-b border-black/5 py-20 md:py-28">
          <div className="absolute inset-0 pointer-events-none">
            {[...Array(18)].map((_, i) => (
              <div
                key={i}
                className="absolute w-1 h-1 rounded-full bg-violet-400/30"
                style={{
                  top: `${10 + ((i * 37) % 80)}%`,
                  left: `${5 + ((i * 53) % 90)}%`,
                }}
              />
            ))}
          </div>
          <div className="relative max-w-4xl mx-auto px-6 text-center">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-violet-200 bg-white text-violet-700 text-xs font-medium mb-6 shadow-sm">
              <BookOpen className="h-3.5 w-3.5" />
              {t("docs.hero.badge")}
            </div>
            <h1 className="text-4xl md:text-5xl font-bold text-gray-900 tracking-tight text-balance mb-4">
              {t("docs.hero.title")}
            </h1>
            <p className="text-gray-500 text-lg leading-relaxed text-pretty max-w-2xl mx-auto mb-8">
              {t("docs.hero.subtitle")}
            </p>
            <div className="relative max-w-lg mx-auto">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400 pointer-events-none" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder={t("docs.hero.searchPlaceholder")}
                className="w-full pl-11 pr-4 py-3 rounded-xl border border-black/10 bg-white shadow-sm text-sm text-gray-800 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-violet-400/50 focus:border-violet-300 transition-all duration-200"
              />
            </div>
          </div>
        </section>
      </Reveal>

      {/* Quick links */}
      <Reveal delay={0.05}>
        <section className="max-w-6xl mx-auto px-6 py-12">
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
            {filteredSections.map((section) => {
              const Icon = section.icon;
              return (
                <motion.a
                  key={section.key}
                  href={`#${section.key}`}
                  whileHover={{ y: -2, scale: 1.02 }}
                  transition={{ duration: 0.2 }}
                  className="flex flex-col items-center gap-2 p-4 rounded-xl bg-white border border-black/8 shadow-[0_1px_2px_rgba(0,0,0,0.04)] hover:shadow-[0_4px_16px_-4px_rgba(0,0,0,0.12)] transition-all duration-200 text-center group"
                >
                  <div className={`p-2 rounded-lg ${section.bg}`}>
                    <Icon className={`h-4 w-4 ${section.color}`} />
                  </div>
                  <span className="text-xs font-medium text-gray-700 leading-tight">{section.label}</span>
                </motion.a>
              );
            })}
          </div>
        </section>
      </Reveal>

      {/* Quick Start */}
      <Reveal delay={0.08}>
        <section id="getting-started" className="max-w-6xl mx-auto px-6 pb-16">
          <div className="bg-white rounded-2xl border border-black/8 shadow-[0_1px_2px_rgba(0,0,0,0.04),0_8px_24px_-8px_rgba(0,0,0,0.08)] overflow-hidden">
            <div className="px-8 py-6 border-b border-black/5 flex items-center gap-3">
              <div className="p-2 rounded-lg bg-violet-100">
                <Zap className="h-4 w-4 text-violet-600" />
              </div>
              <div>
                <h2 className="text-lg font-bold text-gray-900">{t("docs.quickstart.title")}</h2>
                <p className="text-sm text-gray-500">{t("docs.quickstart.subtitle")}</p>
              </div>
            </div>
            <div className="p-8">
              <div className="grid md:grid-cols-3 gap-6">
                {QUICK_START_STEPS.map((step, i) => (
                  <Reveal key={step.step} delay={i * 0.08}>
                    <div className="relative">
                      {i < QUICK_START_STEPS.length - 1 && (
                        <div className="hidden md:block absolute top-5 left-[calc(100%+12px)] w-full h-px bg-gray-200 z-0" />
                      )}
                      <div className="relative z-10">
                        <div className={`w-10 h-10 rounded-full ${step.color} text-white text-sm font-bold flex items-center justify-center mb-4`}>
                          {step.step}
                        </div>
                        <h3 className="font-semibold text-gray-900 mb-2">{step.title}</h3>
                        <p className="text-sm text-gray-500 leading-relaxed">{step.description}</p>
                      </div>
                    </div>
                  </Reveal>
                ))}
              </div>
              <div className="mt-8 pt-6 border-t border-black/5 flex flex-wrap gap-3">
                <Link
                  href="/generate"
                  className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg bg-violet-600 text-white text-sm font-medium hover:bg-violet-700 transition-colors duration-200"
                >
                  {t("docs.quickstart.cta")}
                  <ArrowRight className="h-4 w-4" />
                </Link>
                <Link
                  href="/examples"
                  className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg border border-black/10 bg-white text-gray-700 text-sm font-medium hover:bg-gray-50 transition-colors duration-200"
                >
                  {t("docs.quickstart.examples")}
                  <ExternalLink className="h-4 w-4" />
                </Link>
              </div>
            </div>
          </div>
        </section>
      </Reveal>

      {/* Doc sections grid */}
      <Reveal delay={0.05}>
        <section className="max-w-6xl mx-auto px-6 pb-16">
          <h2 className="text-2xl font-bold text-gray-900 mb-2">{t("docs.sections.title")}</h2>
          <p className="text-gray-500 text-sm mb-8">{t("docs.sections.subtitle")}</p>
          <motion.div
            variants={staggerContainer}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-80px" }}
            className="grid md:grid-cols-2 lg:grid-cols-3 gap-4"
          >
            {filteredSections.map((section, i) => {
              const Icon = section.icon;
              return (
                <motion.div
                  key={section.key}
                  id={section.key}
                  variants={fadeInUp}
                  whileHover={{ y: -2 }}
                  transition={{ duration: 0.2 }}
                  className="bg-white rounded-xl border border-black/8 shadow-[0_1px_2px_rgba(0,0,0,0.04)] hover:shadow-[0_4px_16px_-4px_rgba(0,0,0,0.1)] transition-all duration-200 overflow-hidden"
                >
                  <div className="p-5">
                    <div className="flex items-center gap-3 mb-4">
                      <div className={`p-2 rounded-lg ${section.bg}`}>
                        <Icon className={`h-4 w-4 ${section.color}`} />
                      </div>
                      <h3 className="font-semibold text-gray-900">{section.label}</h3>
                    </div>
                    <ul className="space-y-1.5">
                      {section.items.map((item) => (
                        <li key={item}>
                          <a
                            href="#"
                            className="flex items-center gap-2 text-sm text-gray-600 hover:text-violet-600 transition-colors duration-150 group"
                          >
                            <ChevronRight className="h-3 w-3 text-gray-300 group-hover:text-violet-400 transition-colors" />
                            {item}
                          </a>
                        </li>
                      ))}
                    </ul>
                  </div>
                </motion.div>
              );
            })}
          </motion.div>
        </section>
      </Reveal>

      {/* Code examples */}
      <Reveal delay={0.05}>
        <section id="api" className="max-w-6xl mx-auto px-6 pb-16">
          <div className="bg-white rounded-2xl border border-black/8 shadow-[0_1px_2px_rgba(0,0,0,0.04),0_8px_24px_-8px_rgba(0,0,0,0.08)] overflow-hidden">
            <div className="px-8 py-6 border-b border-black/5 flex items-center gap-3">
              <div className="p-2 rounded-lg bg-pink-100">
                <Terminal className="h-4 w-4 text-pink-600" />
              </div>
              <div>
                <h2 className="text-lg font-bold text-gray-900">{t("docs.codeExamples.title")}</h2>
                <p className="text-sm text-gray-500">{t("docs.codeExamples.subtitle")}</p>
              </div>
            </div>
            <div className="p-8">
              <div className="flex gap-2 mb-6 flex-wrap">
                {CODE_SAMPLES.map((sample) => (
                  <button
                    key={sample.key}
                    onClick={() => setActiveCode(sample.key)}
                    className={`px-4 py-1.5 rounded-lg text-sm font-medium transition-all duration-200 ${
                      activeCode === sample.key
                        ? "bg-violet-600 text-white shadow-sm"
                        : "bg-gray-100 text-gray-600 hover:bg-gray-200"
                    }`}
                  >
                    {sample.label}
                  </button>
                ))}
              </div>
              <CodeBlock
                code={activeSample.code}
                language={activeSample.language}
                label={activeSample.label}
              />
              <div className="mt-4 flex items-center gap-2">
                <Link
                  href="/docs/api"
                  className="inline-flex items-center gap-1.5 text-sm text-violet-600 hover:text-violet-700 font-medium transition-colors duration-200"
                >
                  {t("docs.codeExamples.viewFull")}
                  <ArrowRight className="h-3.5 w-3.5" />
                </Link>
              </div>
            </div>
          </div>
        </section>
      </Reveal>

      {/* Features overview */}
      <Reveal delay={0.05}>
        <section className="max-w-6xl mx-auto px-6 pb-16">
          <div className="grid md:grid-cols-3 gap-4">
            {[
              {
                icon: Layout,
                color: "text-violet-600",
                bg: "bg-violet-100",
                title: t("docs.features.multipage.title"),
                desc: t("docs.features.multipage.desc"),
              },
              {
                icon: GitBranch,
                color: "text-blue-600",
                bg: "bg-blue-100",
                title: t("docs.features.github.title"),
                desc: t("docs.features.github.desc"),
              },
              {
                icon: Download,
                color: "text-emerald-600",
                bg: "bg-emerald-100",
                title: t("docs.features.export.title"),
                desc: t("docs.features.export.desc"),
              },
            ].map((feat, i) => {
              const Icon = feat.icon;
              return (
                <Reveal key={feat.title} delay={i * 0.08}>
                  <div className="bg-white rounded-xl border border-black/8 p-5 shadow-[0_1px_2px_rgba(0,0,0,0.04)] hover:shadow-[0_4px_16px_-4px_rgba(0,0,0,0.1)] transition-all duration-200">
                    <div className={`p-2 rounded-lg ${feat.bg} w-fit mb-3`}>
                      <Icon className={`h-4 w-4 ${feat.color}`} />
                    </div>
                    <h3 className="font-semibold text-gray-900 mb-1.5">{feat.title}</h3>
                    <p className="text-sm text-gray-500 leading-relaxed">{feat.desc}</p>
                  </div>
                </Reveal>
              );
            })}
          </div>
        </section>
      </Reveal>

      {/* FAQ */}
      <Reveal delay={0.05}>
        <section className="max-w-6xl mx-auto px-6 pb-16">
          <div className="bg-white rounded-2xl border border-black/8 shadow-[0_1px_2px_rgba(0,0,0,0.04),0_8px_24px_-8px_rgba(0,0,0,0.08)] overflow-hidden">
            <div className="px-8 py-6 border-b border-black/5 flex items-center justify-between flex-wrap gap-4">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-orange-100">
                  <FileText className="h-4 w-4 text-orange-600" />
                </div>
                <div>
                  <h2 className="text-lg font-bold text-gray-900">{t("docs.faq.title")}</h2>
                  <p className="text-sm text-gray-500">{t("docs.faq.subtitle")}</p>
                </div>
              </div>
              <Link
                href="/faq"
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-violet-600 text-white text-sm font-medium hover:bg-violet-700 transition-colors duration-200"
              >
                {t("docs.faq.viewAll")}
                <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
            <div className="p-8 space-y-3">
              {FAQ_ITEMS.map((item) => (
                <FaqItem key={item.q} q={item.q} a={item.a} />
              ))}
            </div>
          </div>
        </section>
      </Reveal>

      {/* CTA */}
      <Reveal delay={0.05}>
        <section className="max-w-6xl mx-auto px-6 pb-20">
          <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-violet-600 via-violet-700 to-purple-800 p-12 text-center shadow-[0_8px_32px_-8px_rgba(109,40,217,0.4)]">
            <div className="absolute inset-0 pointer-events-none">
              {[...Array(12)].map((_, i) => (
                <div
                  key={i}
                  className="absolute w-1 h-1 rounded-full bg-white/20"
                  style={{
                    top: `${10 + ((i * 41) % 80)}%`,
                    left: `${5 + ((i * 67) % 90)}%`,
                  }}
                />
              ))}
            </div>
            <div className="relative">
              <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-white/20 bg-white/10 text-white text-xs font-medium mb-5">
                <Sparkles className="h-3.5 w-3.5" />
                {t("docs.cta.badge")}
              </div>
              <h2 className="text-3xl md:text-4xl font-bold text-white tracking-tight mb-3">
                {t("docs.cta.title")}
              </h2>
              <p className="text-violet-200 text-base leading-relaxed mb-8 max-w-md mx-auto">
                {t("docs.cta.subtitle")}
              </p>
              <Link
                href="/generate"
                className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-white text-violet-700 font-semibold text-sm hover:bg-violet-50 transition-colors duration-200 shadow-sm"
              >
                {t("docs.cta.button")}
                <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
          </div>
        </section>
      </Reveal>
    </main>
  );
}