"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Sparkles, Zap, Code2, Eye, Download, GitBranch, Star, ArrowRight, ChevronDown, ChevronUp } from 'lucide-react';
import { Reveal } from "@/components/Reveal";
import { staggerContainer, fadeInUp } from "@/lib/motion";

interface ChangelogEntry {
  version: string;
  date: string;
  tag: "major" | "minor" | "patch" | "beta";
  title: string;
  summary: string;
  changes: {
    type: "new" | "improved" | "fixed" | "removed";
    text: string;
  }[];
}

const CHANGELOG: ChangelogEntry[] = [
  {
    version: "2.4.0",
    date: "June 12, 2025",
    tag: "major",
    title: "Multi-page generation and GitHub push",
    summary: "Generate complete multi-page websites in a single prompt, and push your code directly to any GitHub repository with one click.",
    changes: [
      { type: "new", text: "Multi-page site generation — describe your full site and Builder creates every route automatically." },
      { type: "new", text: "GitHub push integration — connect your repo and deploy straight from the Builder dashboard." },
      { type: "new", text: "Custom domain hints — Builder now suggests optimal Vercel and Netlify config for your generated site." },
      { type: "improved", text: "GPT-4o prompt understanding improved for complex, multi-section briefs." },
      { type: "improved", text: "Live preview now streams section-by-section as the AI writes each component." },
      { type: "fixed", text: "Fixed an edge case where Tailwind purge removed classes used only in generated code." },
    ],
  },
  {
    version: "2.3.1",
    date: "May 28, 2025",
    tag: "patch",
    title: "Performance and stability fixes",
    summary: "A focused patch addressing preview latency, export reliability, and a handful of reported TypeScript output issues.",
    changes: [
      { type: "fixed", text: "Reduced live preview cold-start time from ~4s to under 800ms." },
      { type: "fixed", text: "Code export ZIP now correctly includes all generated image assets." },
      { type: "fixed", text: "TypeScript strict-mode errors in generated form components resolved." },
      { type: "improved", text: "Sandbox container recycling is now 40% faster between generations." },
    ],
  },
  {
    version: "2.3.0",
    date: "May 14, 2025",
    tag: "minor",
    title: "Design system tokens and dark mode output",
    summary: "Builder now generates sites with a full design-token layer, and can produce dark-mode-ready output on request.",
    changes: [
      { type: "new", text: "Design token generation — every site now ships with a `globals.css` `:root` block of CSS custom properties." },
      { type: "new", text: "Dark mode output — add 'dark mode' to your prompt and Builder wires up Tailwind's dark variant automatically." },
      { type: "new", text: "Framer Motion animations included by default in all new generations." },
      { type: "improved", text: "Heading hierarchy is now enforced — generated pages always have exactly one `<h1>`." },
      { type: "fixed", text: "Fixed missing `alt` attributes on generated `<img>` tags." },
      { type: "fixed", text: "Resolved hydration mismatch in generated pages that used `Math.random()` during render." },
    ],
  },
  {
    version: "2.2.0",
    date: "April 30, 2025",
    tag: "minor",
    title: "Studio plan and credit top-ups",
    summary: "Introducing the Studio plan with 500 credits, plus a new top-up flow so you never run out mid-project.",
    changes: [
      { type: "new", text: "Studio plan launched — 500 credits, priority support, and early access to new features." },
      { type: "new", text: "Credit top-up flow — purchase additional credits without changing your plan." },
      { type: "new", text: "Credit usage dashboard — see a breakdown of credits spent per project." },
      { type: "improved", text: "Pricing page redesigned with clearer per-credit cost comparison." },
    ],
  },
  {
    version: "2.1.0",
    date: "April 10, 2025",
    tag: "minor",
    title: "Examples gallery and prompt templates",
    summary: "Browse real AI-generated sites in the new Examples gallery, and start from a curated prompt template instead of a blank slate.",
    changes: [
      { type: "new", text: "Examples gallery — 30+ real sites generated by Builder, filterable by category." },
      { type: "new", text: "Prompt templates — choose from SaaS landing page, portfolio, e-commerce, blog, and more." },
      { type: "new", text: "One-click remix — open any example in the generator pre-filled with its original prompt." },
      { type: "improved", text: "Generator input now supports multi-line prompts with Shift+Enter." },
      { type: "fixed", text: "Fixed a bug where the preview iframe would not resize correctly on mobile viewports." },
    ],
  },
  {
    version: "2.0.0",
    date: "March 20, 2025",
    tag: "major",
    title: "Builder 2.0 — complete rebuild on Next.js 14",
    summary: "Builder has been rebuilt from the ground up on Next.js 14 App Router, with a new UI, faster generation engine, and a credit-based pricing model.",
    changes: [
      { type: "new", text: "Rebuilt on Next.js 14 App Router — server components, streaming, and optimised images out of the box." },
      { type: "new", text: "Credit-based pricing — pay only for what you build, credits never expire." },
      { type: "new", text: "New dashboard with project history, live preview, and one-click export." },
      { type: "new", text: "GPT-4o integration replaces the previous GPT-3.5 backend." },
      { type: "improved", text: "Average generation time reduced from 3 minutes to under 60 seconds." },
      { type: "removed", text: "Legacy subscription plans retired — existing subscribers were migrated to equivalent credit balances." },
    ],
  },
  {
    version: "1.9.2",
    date: "February 5, 2025",
    tag: "beta",
    title: "Beta: internationalization and locale support",
    summary: "Early access to i18n output — Builder can now generate sites with next-intl wired up and message catalogs pre-filled.",
    changes: [
      { type: "new", text: "i18n output (beta) — add 'multilingual' to your prompt to get a next-intl setup with en/es catalogs." },
      { type: "new", text: "Locale toggle component generated automatically for i18n sites." },
      { type: "fixed", text: "Fixed TypeScript errors in generated API route handlers." },
    ],
  },
];

const TAG_STYLES: Record<ChangelogEntry["tag"], string> = {
  major: "bg-violet-100 text-violet-700 border border-violet-200",
  minor: "bg-blue-100 text-blue-700 border border-blue-200",
  patch: "bg-emerald-100 text-emerald-700 border border-emerald-200",
  beta: "bg-orange-100 text-orange-700 border border-orange-200",
};

const CHANGE_TYPE_STYLES: Record<string, string> = {
  new: "bg-emerald-100 text-emerald-700",
  improved: "bg-blue-100 text-blue-700",
  fixed: "bg-amber-100 text-amber-700",
  removed: "bg-red-100 text-red-600",
};

const CHANGE_TYPE_LABELS: Record<string, string> = {
  new: "New",
  improved: "Improved",
  fixed: "Fixed",
  removed: "Removed",
};

function ChangelogCard({ entry, index }: { entry: ChangelogEntry; index: number }) {
  const [expanded, setExpanded] = useState(index === 0);

  return (
    <Reveal delay={index * 0.06}>
      <div className="bg-white border border-black/[0.07] rounded-2xl shadow-[0_1px_2px_rgba(0,0,0,0.04),0_8px_24px_-8px_rgba(0,0,0,0.08)] overflow-hidden">
        <button
          className="w-full text-left px-6 py-5 flex items-start gap-4 hover:bg-slate-50/60 transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-500 focus-visible:ring-inset"
          onClick={() => setExpanded((v) => !v)}
          aria-expanded={expanded}
        >
          <div className="flex-1 min-w-0">
            <div className="flex flex-wrap items-center gap-2 mb-2">
              <span className="font-mono text-sm font-semibold text-slate-800 bg-slate-100 px-2 py-0.5 rounded-md">
                v{entry.version}
              </span>
              <span className={`text-xs font-semibold px-2 py-0.5 rounded-full capitalize ${TAG_STYLES[entry.tag]}`}>
                {entry.tag}
              </span>
              <span className="text-xs text-slate-400 ml-auto">{entry.date}</span>
            </div>
            <h2 className="text-base font-semibold text-slate-900 leading-snug">{entry.title}</h2>
            {!expanded && (
              <p className="text-sm text-slate-500 mt-1 leading-relaxed line-clamp-1">{entry.summary}</p>
            )}
          </div>
          <div className="flex-shrink-0 mt-0.5 text-slate-400">
            {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
          </div>
        </button>

        {expanded && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.3, ease: "easeOut" }}
            className="border-t border-black/[0.06]"
          >
            <div className="px-6 py-5">
              <p className="text-sm text-slate-600 leading-relaxed mb-5">{entry.summary}</p>
              <ul className="space-y-2.5">
                {entry.changes.map((change, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <span
                      className={`inline-block text-[10px] font-bold uppercase tracking-wide px-1.5 py-0.5 rounded mt-0.5 flex-shrink-0 ${CHANGE_TYPE_STYLES[change.type]}`}
                    >
                      {CHANGE_TYPE_LABELS[change.type]}
                    </span>
                    <span className="text-sm text-slate-700 leading-relaxed">{change.text}</span>
                  </li>
                ))}
              </ul>
            </div>
          </motion.div>
        )}
      </div>
    </Reveal>
  );
}

const STATS = [
  { value: "2.4", label: "Current version", icon: Star },
  { value: "18", label: "Releases this year", icon: GitBranch },
  { value: "60+", label: "Improvements shipped", icon: Zap },
  { value: "100%", label: "Backward compatible", icon: Code2 },
];

export default function ChangelogPage() {
  return (
    <main className="min-h-screen bg-[#f5f5f7]">
      {/* Hero */}
      <Reveal>
        <section className="pt-20 pb-12 px-4 text-center">
          <div className="inline-flex items-center gap-1.5 bg-white border border-violet-200 text-violet-700 text-xs font-semibold px-3 py-1.5 rounded-full mb-6 shadow-sm">
            <Sparkles className="h-3.5 w-3.5" />
            What&apos;s new
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-slate-900 tracking-tight text-balance mb-4">
            Changelog
          </h1>
          <p className="text-base text-slate-500 max-w-xl mx-auto leading-relaxed text-pretty">
            Every improvement, fix, and new feature shipped to Builder. Updated with every release.
          </p>
        </section>
      </Reveal>

      {/* Stats row */}
      <Reveal delay={0.1}>
        <section className="px-4 pb-14">
          <div className="max-w-4xl mx-auto">
            <motion.div
              variants={staggerContainer}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: "-60px" }}
              className="grid grid-cols-2 md:grid-cols-4 gap-4"
            >
              {STATS.map((stat, i) => (
                <motion.div
                  key={stat.label}
                  variants={fadeInUp}
                  className="bg-white border border-black/[0.07] rounded-2xl px-5 py-5 text-center shadow-[0_1px_2px_rgba(0,0,0,0.04),0_4px_12px_-4px_rgba(0,0,0,0.06)]"
                >
                  <stat.icon className="h-5 w-5 text-violet-500 mx-auto mb-2" aria-hidden="true" />
                  <div className="text-2xl font-bold text-slate-900 tracking-tight">{stat.value}</div>
                  <div className="text-xs text-slate-500 mt-0.5">{stat.label}</div>
                </motion.div>
              ))}
            </motion.div>
          </div>
        </section>
      </Reveal>

      {/* Filter bar */}
      <Reveal delay={0.05}>
        <section className="px-4 pb-8">
          <div className="max-w-4xl mx-auto flex flex-wrap items-center gap-2">
            <span className="text-xs font-semibold text-slate-500 uppercase tracking-wide mr-1">Filter:</span>
            {(["all", "major", "minor", "patch", "beta"] as const).map((tag) => (
              <span
                key={tag}
                className={`text-xs font-semibold px-3 py-1 rounded-full cursor-default capitalize border ${
                  tag === "all"
                    ? "bg-violet-600 text-white border-violet-600"
                    : TAG_STYLES[tag as ChangelogEntry["tag"]] ?? "bg-slate-100 text-slate-600 border-slate-200"
                }`}
              >
                {tag === "all" ? "All releases" : tag}
              </span>
            ))}
          </div>
        </section>
      </Reveal>

      {/* Entries */}
      <section className="px-4 pb-24">
        <div className="max-w-4xl mx-auto space-y-4">
          {CHANGELOG.map((entry, i) => (
            <ChangelogCard key={entry.version} entry={entry} index={i} />
          ))}
        </div>
      </section>

      {/* CTA */}
      <Reveal>
        <section className="px-4 pb-24">
          <div className="max-w-4xl mx-auto">
            <div className="relative overflow-hidden bg-gradient-to-br from-violet-600 via-violet-700 to-purple-800 rounded-3xl px-8 py-14 text-center shadow-[0_8px_40px_-8px_rgba(124,58,237,0.5)]">
              <div className="absolute inset-0 opacity-20 pointer-events-none"
                style={{ backgroundImage: "radial-gradient(circle at 20% 50%, rgba(255,255,255,0.15) 0%, transparent 60%), radial-gradient(circle at 80% 20%, rgba(255,255,255,0.1) 0%, transparent 50%)" }}
              />
              <div className="relative z-10">
                <div className="inline-flex items-center gap-1.5 bg-white/10 border border-white/20 text-white text-xs font-semibold px-3 py-1.5 rounded-full mb-5">
                  <Eye className="h-3.5 w-3.5" />
                  Stay up to date
                </div>
                <h2 className="text-3xl md:text-4xl font-bold text-white tracking-tight mb-3">
                  Ready to build?
                </h2>
                <p className="text-violet-200 text-sm leading-relaxed max-w-md mx-auto mb-8">
                  Every release makes Builder faster and smarter. Start generating production-ready websites today.
                </p>
                <a
                  href="/generate"
                  className="inline-flex items-center gap-2 bg-white text-violet-700 font-semibold text-sm px-6 py-3 rounded-xl hover:bg-violet-50 transition-colors duration-200 shadow-md"
                >
                  Start Building
                  <ArrowRight className="h-4 w-4" />
                </a>
              </div>
            </div>
          </div>
        </section>
      </Reveal>
    </main>
  );
}